name: "Staging to Parent with composer"
description: "Update parent on every staging change."

on:
  workflow_call:
    inputs:
      branch: # name of the branch or env
        description: "Name of the branch, same as environment. Available: [staging, production]"
        required: true
        default: ""
      composer_parent_path: # folder of the parent repo to update composer dependency
        description: "Where is the composer file to update"
        required: true
        default: ""
      composer_project_path: # folder of the parent repo to update composer dependency
        description: "Where is the project cloned"
        required: true
        default: ""
      secret: # id of input
        description: "Secret to update parent repo"
        required: true
        default: ""
      version: # id of input
        description: "Tag version"
        required: true
        default: ""
      composer_wpmudev: # id of input
        description: "Secret to resolve wpmudev plugin"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t my-image:${{ github.sha }} .

      - name: Push Docker image to registry
        run: |
          docker push my-image:${{ github.sha }}

      - name: Deploy to staging
        run: |
          docker run my-image:${{ github.sha }} \
            "${{ inputs.branch }}" \
            "${{ inputs.composer_parent_path }}" \
            "${{ inputs.composer_project_path }}" \
            "${{ inputs.secret }}" \
            "${{ inputs.version }}" \
            "${{ inputs.composer_wpmudev }}" \
            "${{ secrets.YOAST_PREMIUM }}"
